# Generated by Django 3.2.5 on 2021-09-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'hotel',
                'verbose_name_plural': 'hotel',
            },
        ),
    ]
